### ISSUE TITLE
Grapher doesn't update with "Inch Machine Screw" a parent of "ASME B18.6.3"

### ISSUE THREAD

**Issue by crosjef** [paul-go/Truth-Grapher#2]
If I click on a machine screw (e.g. line 510), the grapher doesn't resolve the ASME B18.6.3 Round 0 side of the tree. If I go to ASME B18.6.3 and remove "Inch Machine Screw" as a parent, then the grapher fully draws the tree for the inch machine screws.

[Machine Screw with SKUs.txt](https://github.com/paul-go/Truth/files/2989470/Machine.Screw.with.SKUs.txt)

**Comment by paul-go** [comment]
This appears to be working in the latest build, even with the 766 errors in the file provided.

**Comment by crosjef** [comment]
Verified
